name: fashion_customer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+12

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  after_layout: ^1.1.0
  animations: ^2.0.2
  auto_size_text: ^3.0.0
  cloud_firestore: ^3.1.10
  cupertino_icons: ^1.0.2
  file_saver: 
    git:
      url: https://github.com/incrediblezayed/file_saver.git
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.13
  firebase_storage: ^10.2.12
  flutter:
    sdk: flutter
  flutter_local_notifications: ^9.4.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^1.0.3
  geocode: ^1.0.1
  geolocator: ^8.2.0
  get_it: ^7.2.0
  google_fonts: ^2.3.1
  google_maps_flutter: ^2.1.3
  http: ^0.13.4
  image_cropper: ^1.5.1
  image_picker: ^0.8.5
  intl: ^0.17.0
  pdf: ^3.7.4
  shared_preferences: ^2.0.13
  smooth_star_rating_null_safety: ^1.0.4+2
  url_launcher: ^6.0.20
  flutter_native_splash: ^2.1.6
  cached_network_image: ^3.2.1
  badges: ^2.0.3
  get: ^4.6.5

dev_dependencies:
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - Icons/